/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "React Native for Windows + macOS",
  "tagline": "Build native Windows & macOS apps with Javascript and React",
  "url": "https://microsoft.github.io",
  "baseUrl": "/react-native-windows/",
  "organizationName": "microsoft",
  "projectName": "react-native-windows",
  "scripts": [
    "https://cdn.jsdelivr.net/npm/focus-visible@5.0.2/dist/focus-visible.min.js",
    "https://platform.twitter.com/widgets.js",
    "https://buttons.github.io/buttons.js",
    "https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js",
    "/react-native-windows/js/code-block-buttons.js",
    "/react-native-windows/js/nav-buttons.js"
  ],
  "stylesheets": [
    "/react-native-windows/css/code-block-buttons.css"
  ],
  "favicon": "img/favicon.ico",
  "customFields": {
    "repoUrl": "https://github.com/microsoft/react-native-windows",
    "defaultVersionShown": "0.71",
    "customFields": {
      "users": [
        {
          "header": "Xbox app on Windows",
          "category": "1st party",
          "description": [
            "The Xbox app on Windows lets users explore the catalogue of games available through Xbox Game Pass, chat with friends, and more.",
            "Written in React Native, the Xbox app has a premium user experience including buttery smooth animations and video playback. "
          ],
          "link": "https://www.microsoft.com/store/productId/9MV0B5HZVK9Z",
          "img": "img/XboxStoreApp.gif"
        },
        {
          "header": "Microsoft Store on Xbox",
          "category": "1st party",
          "description": [
            "The Microsoft Store app on Xbox consoles has been rewritten from the ground up to be faster, safer, and easier to use than ever before.",
            "The new Microsoft Store on Xbox is more than twice as fast as before, because it uses the native capabilities of the platform via React Native."
          ],
          "link": "https://news.xbox.com/en-us/2020/08/03/new-microsoft-store-coming-to-xbox-insiders/",
          "logo": "img/XBox.png"
        },
        {
          "header": "Microsoft Office",
          "category": "1st party",
          "description": [
            "Microsoft Office leverages React Native in several experiences across the suite of Office apps including Word, Excel, and PowerPoint.",
            "Some examples include the modern commenting experience, privacy dialog, and unity canvas. These experiences ship across both mobile and desktop, including on macOS and Windows."
          ],
          "link": "http://office.com",
          "logo": [
            "img/Office.png"
          ]
        },
        {
          "header": "React Native Gallery",
          "category": "1st party",
          "description": [
            "The React Native Gallery app showcases the components and capabilities of React Native for Windows.",
            "You can find core components provided by the platform in addition to wrapped WinUI controls and common community modules. "
          ],
          "logo": "https://github.com/microsoft/react-native-gallery/blob/main/windows/rngallery/Assets/Square44x44Logo.altform-lightunplated_targetsize-256.png?raw=true",
          "link": "https://www.microsoft.com/store/productId/9NPG0B292H4R"
        },
        {
          "header": "Power Apps",
          "category": "1st party",
          "description": "Power Apps help you build professional-grade apps the easy way, and increase agility across your organization by enabling you to rapidly build low-code apps to modernize processes and solve tough challenges.",
          "link": "https://powerapps.microsoft.com/",
          "logo": "img/PowerApps.png"
        },
        {
          "header": "Web Template Studio",
          "category": "1st party",
          "description": "Microsoft Web Template Studio (aka WebTS) is a Visual Studio Code Extension that accelerates the creation of a new Web or React Native application using a wizard-based experience.",
          "link": "https://github.com/microsoft/WebTemplateStudio",
          "logo": "https://wasteamaccount.gallerycdn.vsassets.io/extensions/wasteamaccount/webtemplatestudio-dev-nightly/0.7.2117301/1624436773361/Microsoft.VisualStudio.Services.Icons.Default"
        },
        {
          "header": "Fluent UI React Native",
          "category": "1st party",
          "description": "FluentUI React Native is a JavaScript component library that provides developers with controls that are part of the Fluent Design System. These controls are built on React Native and fully customizable.",
          "link": "https://github.com/microsoft/fluentui-react-native",
          "logo": "https://www.microsoft.com/design/fluent/assets/favicons/favicon-192.png"
        },
        {
          "header": "BabylonJS",
          "category": "3rd party",
          "description": [
            "Babylon.JS is a powerful, beautiful, simple, and open game and rendering engine packed into a friendly JS framework.",
            "Babylon React Native brings the power of Babylon to React Native apps on Android, iOS, and Windows."
          ],
          "link": "https://github.com/babylonjs/babylonreactnative",
          "logo": "https://github.com/BabylonJS/Brand-Toolkit/blob/a4a72b1b87a3ffd68657fd5cb82da24691f291b8/babylon_logo/fullColor/babylon_logo_color.png?raw=true"
        },
        {
          "header": "Facebook Messenger (Desktop)",
          "category": "3rd party",
          "logo": "img/Messenger.png",
          "description": "The React Native team is partnering deeply with Messenger Desktop to deliver on one of the top company initiatives, Remote Presence. Messenger Desktop is using React Native to bring a delightful native video calling experience to Windows and macOS. ",
          "link": "https://twitter.com/reactnative/status/1286061933293010944?s=20"
        },
        {
          "header": "Knomadix",
          "category": "3rd party",
          "logo": "https://www.knomadix.com/wp-content/uploads/2015/05/Knomadix-Bug-transparent.png",
          "description": "Knomadix partnered with Microsoft to migrate the Knomadix Backpack app to the Microsoft Store using React Native for Windows – which will enable students to learn in an offline mode even when they’re not connected to the internet.",
          "link": "https://www.knomadix.com/knomadix-releases-react-native-windows-version-of-knomadix-backpack/#:~:text=Knomadix%20offered%20to%20collaborate%20with%20Dynabook%20and%20the,develop%20a%20Universal%20Windows%20App%20using%20React%20Native."
        },
        {
          "header": "Mashreq",
          "category": "3rd party",
          "logo": "https://www.mashreqbank.com/favicon.ico",
          "description": [
            "Mashreq bank developed an application Universal Banker App with React Native to empower frontline employees working at branches to serve customers across a broad range of inquiries and journeys.",
            "The application helped them to increase the proximity with the customer, improving the customer experience and reducing the service time."
          ],
          "link": "https://techcommunity.microsoft.com/t5/windows-dev-appconsult/how-mashreq-bank-is-using-react-native-for-windows-to-bring-new/ba-p/2421056#:~:text=Mashreq%20bank%20developed%20an%20application%20Universal%20Banker%20App,the%20customer%20experience%20and%20reducing%20the%20service%20time."
        }
      ]
    }
  },
  "onBrokenLinks": "log",
  "onBrokenMarkdownLinks": "log",
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "editUrl": "https://github.com/microsoft/react-native-windows-samples/blob/main/docs/",
          "path": "../docs",
          "sidebarPath": "../website/sidebars.json"
        },
        "blog": {
          "path": "blog"
        },
        "theme": {
          "customCss": "../src/css/customTheme.css"
        }
      }
    ]
  ],
  "plugins": [],
  "themeConfig": {
    "navbar": {
      "title": "React Native for Windows + macOS",
      "logo": {
        "src": "img/header_logo.svg"
      },
      "items": [
        {
          "to": "docs/next/getting-started",
          "label": "Docs",
          "position": "left"
        },
        {
          "to": "docs/next/flyout-component",
          "label": "APIs",
          "position": "left"
        },
        {
          "href": "https://devblogs.microsoft.com/react-native/",
          "label": "Blog",
          "position": "left"
        },
        {
          "to": "/resources",
          "label": "Resources",
          "position": "left"
        },
        {
          "href": "https://github.com/microsoft/react-native-windows-samples/tree/main/samples",
          "label": "Samples",
          "position": "left"
        },
        {
          "to": "/support",
          "label": "Support",
          "position": "left"
        }
      ],
      "hideOnScroll": false
    },
    "image": "img/undraw_online.svg",
    "footer": {
      "links": [],
      "logo": {
        "src": "img/header_logo.png"
      },
      "style": "light"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
